version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crowdiq_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: crowdiq_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: crowdiq_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: crowdiq_opensearch
    environment:
      - cluster.name=crowdiq-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: crowdiq_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  mailpit:
    image: axllent/mailpit
    container_name: crowdiq_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  redis_data:
  opensearch_data:
